#!/bin/sh

make even

declare -i sum_odd=0
declare -i sum_even=0
declare -i result=0

while [ $# -ne 0 ]
do
    ./even $1
    result=$?
        
    if [ $result -eq 0 ]
    then 
        sum_even=$(($sum_even + $1))
       
    elif [ $result -eq 1 ]
    then 
        sum_odd=$(($sum_odd + $1))
    else 
        echo $"Argument wich is no number found. Aborting the Script."
        exit 1
    fi
    shift

done

echo $"Sum of even numbers: "$sum_even
echo $"Sum of odd numbers: "$sum_odd